### ISSUE TITLE
Unable to close YouTube video in "About Wheatley" Page 

### ISSUE THREAD

**Issue by Thanusha12** [hlxsites/sazerac-wheatleyvodka#125]
1. The video doesn't open up to a pop-up which can be closed like we have now in production.

![image](https://github.com/hlxsites/sazerac-wheatleyvodka/assets/122380883/ef74afe3-7360-491d-a12d-f8da732de05f)

2. All the content in this page needs be centered(requires margin/padding). Please see below attached 

![image](https://github.com/hlxsites/sazerac-wheatleyvodka/assets/122380883/d72a2d6b-585c-49f2-b7ee-4bcc5b8432b1)

currently the content is spread out without margin/padding like below : 

![image](https://github.com/hlxsites/sazerac-wheatleyvodka/assets/122380883/8825b47a-11cf-495d-acca-d85bac9e1dc0)

3. The font used for the Author Name is different. It needs to be "HCo Ringside Extra Wide",sans-serif "

![image](https://github.com/hlxsites/sazerac-wheatleyvodka/assets/122380883/655cb5a5-72da-42fb-b965-3ce5a405854e)

**Comment by karlpauls** [comment]
@Thanusha12, I think I addressed the styling issues you mention in this issue. The video player is not changed yet but 2 and 3 from above should be fixed.
