### ISSUE TITLE
Content Bug - This can be corrected post launch

### ISSUE THREAD

**Issue by Thanusha12** [hlxsites/sazerac-wheatleyvodka#135]
1.The content is switched on the "10x distilled" and "why wheat" tiles. The live site is on the left and the franklin site is on the right.

![image](https://github.com/hlxsites/sazerac-wheatleyvodka/assets/122380883/900509cb-e38a-46f8-8cd3-9161b2828f52)

**Comment by cziegeler** [comment]
Fixed, see https://main--sazerac-wheatleyvodka--hlxsites.hlx.live/about-wheatley
