### ISSUE TITLE
implement style for cocktails

### ISSUE THREAD

**Issue by RemoLiechti** [hlxsites/sazerac-wheatleyvodka#16]
- implement the css styles needed for the cocktails pages
- add templating mechanism as described below
- use bulk metadata for the template path
- create the template file for cocktails, providing the pocketguide block for all

**Comment by cziegeler** [comment]
We should use templating for the cocktails page. The word document for a cocktail should be "plain" word, no blocks.
We create a template word document which uses a (empty) cocktail block, and a block for the pocketguide.
We use global metadata and set a "Template" metadata for each cocktail page.
When the page is loaded, the Template metadata is explored, if it is set, the template will be loaded, the main contents replaced with the template - and the original page main content will be put inside the template. Then normal rendering continues
