### ISSUE TITLE
decide on what to do with /faq/ urls?

### ISSUE THREAD

**Issue by RemoLiechti** [hlxsites/sazerac-wheatleyvodka#21]
it seems like none of the FAQ urls actually display something. I rather believe that those URLs are somehow generated in the sitemap by wordpress as the FAQ is added on the [about](https://www.wheatleyvodka.com/about-wheatley/) page.
I guess we can simply add the FAQ on the about page itself and ignore those urls.

**Comment by karlpauls** [comment]
Agreed.
