### ISSUE TITLE
implement the age verrification overlay

### ISSUE THREAD

**Issue by RemoLiechti** [hlxsites/sazerac-wheatleyvodka#23]
hint: use inkognito mode to always get it
implement a mechanism that on all pages, when accessing, the visitor has to confirm the age, with a yes/no button.
yes - currently, a cookie is set
no - tells to come back and redirects to https://www.responsibility.org/

ensure a way to bypass this popup as the LHS tests will run into this all the time, which affects performance for sure.

**Comment by chhaack** [comment]
replaced by https://github.com/hlxsites/sazerac-wheatleyvodka/issues/45
