### ISSUE TITLE
implement the 404 page

### ISSUE THREAD

**Issue by RemoLiechti** [hlxsites/sazerac-wheatleyvodka#26]
implement a proper 404 page, the current one seems not to be a nice one...
https://www.wheatleyvodka.com/cocktails/cucumber-collins/foobar

**Comment by cziegeler** [comment]
As we migrate from a site where the URLs ended in a slash (see #25 ) we should add some logic to the 404 handler:
- if the URL ends in a slash, do a redirect to the URL without a slash

**Comment by RemoLiechti** [comment]
goeal: hero, button, 404, centered, no scrolling
