### ISSUE TITLE
Document original lighthouse score

### ISSUE THREAD

**Issue by karlpauls** [hlxsites/sazerac-wheatleyvodka#4]
We should establish the list of urls and document (screenshot plus values captured in a table) the respective pagespeed results (https://pagespeed.web.dev/).

Probably a good idea to create a new top-level docs folder and a subfolder in there with results.

**Comment by RemoLiechti** [comment]
not capturing these urls:
https://www.wheatleyvodka.com/hello-world/
https://www.wheatleyvodka.com/category/uncategorized/
https://www.wheatleyvodka.com/quotes/greg-1/
https://www.wheatleyvodka.com/quotes/greg-2/
https://www.wheatleyvodka.com/quotes/matthew-wesolik/
https://www.wheatleyvodka.com/author/missiondata/

capturing below urls:
https://www.wheatleyvodka.com/
https://www.wheatleyvodka.com/about-wheatley/
https://www.wheatleyvodka.com/locator/
https://www.wheatleyvodka.com/cocktails/
https://www.wheatleyvodka.com/faqs/why-are-some-vodkas-distilled-more-than-once/
https://www.wheatleyvodka.com/faqs/how-many-times-is-wheatley-vodka-distilled-and-why/
https://www.wheatleyvodka.com/faqs/whats-the-difference-in-distilling-vodka-in-a-pot-still-versus-a-columnar-still/
https://www.wheatleyvodka.com/faqs/what-is-a-craft-distillery/
https://www.wheatleyvodka.com/faqs/what-types-of-ingredients-go-into-a-good-vodka/
https://www.wheatleyvodka.com/faqs/why-do-some-vodka-brands-distill-their-spirits-in-small-batches/
https://www.wheatleyvodka.com/faqs/isnt-vodka-just-distilled-from-potatoes/
https://www.wheatleyvodka.com/faqs/what-does-it-mean-when-a-vodka-is-distilled/
https://www.wheatleyvodka.com/faqs/is-all-vodka-the-same/
https://www.wheatleyvodka.com/faqs/doesnt-vodka-have-to-be-distilled-in-russia/
https://www.wheatleyvodka.com/faqs/does-distilling-the-vodka-more-make-it-better/
https://www.wheatleyvodka.com/faqs/whats-the-difference-between-corn-and-wheat-based-vodka/
https://www.wheatleyvodka.com/cocktails/wheatley-vodka-club/
https://www.wheatleyvodka.com/cocktails/cucumber-collins/
https://www.wheatleyvodka.com/cocktails/la-luna-rossa/
https://www.wheatleyvodka.com/cocktails/flatiron-flip/
https://www.wheatleyvodka.com/cocktails/garden-of-eden/
https://www.wheatleyvodka.com/cocktails/romapolitan/
https://www.wheatleyvodka.com/cocktails/snooze-alarm/
https://www.wheatleyvodka.com/cocktails/dont-touch-my-bowl/
https://www.wheatleyvodka.com/cocktails/my-pizza-is-sour/
https://www.wheatleyvodka.com/cocktails/green-machine/
https://www.wheatleyvodka.com/cocktails/cocktails-of-the-castaway/
https://www.wheatleyvodka.com/cocktails/the-buck-stops-here/
https://www.wheatleyvodka.com/cocktails/gone-with-the-wind/
https://www.wheatleyvodka.com/cocktails/dad-joke/
https://www.wheatleyvodka.com/cocktails/wheatley-vodka-martini/
https://www.wheatleyvodka.com/cocktails/wheatley-vodka-moscow-mule/
https://www.wheatleyvodka.com/cocktails/wheatley-vodka-screwdriver/
https://www.wheatleyvodka.com/cocktails/wheatley-vodka-mint-lemonade/
https://www.wheatleyvodka.com/cocktails/wheatley-vodka-sweet-tea-mint-julep/
https://www.wheatleyvodka.com/cocktails/wheatley-vodka-pineapple-mint-julep/
https://www.wheatleyvodka.com/cocktails/all-you-can-wheat/
https://www.wheatleyvodka.com/cocktails/green-jacket/
https://www.wheatleyvodka.com/cocktails/wheatley-far-east-mule/
https://www.wheatleyvodka.com/cocktails/wheatley-vodka-greyhound/
https://www.wheatleyvodka.com/cocktails/wheatley-winter-wonderful/
https://www.wheatleyvodka.com/cocktails/spiced-punch/
https://www.wheatleyvodka.com/cocktails/its-always-sunny/
https://www.wheatleyvodka.com/cocktails/wheatley-vodka-club-2/
https://www.wheatleyvodka.com/cocktails/village-mary/
https://www.wheatleyvodka.com/cocktails/beetopolitan/
https://www.wheatleyvodka.com/cocktails/the-gallagher/
https://www.wheatleyvodka.com/cocktails/the-pineapple-bottom/
https://www.wheatleyvodka.com/cocktails/summertime-romp/
https://www.wheatleyvodka.com/cocktails/fire-on-the-water/
https://www.wheatleyvodka.com/cocktails/bottoms-up/
https://www.wheatleyvodka.com/cocktails/chasing-waterfalls/
https://www.wheatleyvodka.com/cocktails/down-the-rabbit-hole/
https://www.wheatleyvodka.com/cocktails/wheatley-bloody-mary/
https://www.wheatleyvodka.com/cocktails/wheatley-white-russian/
https://www.wheatleyvodka.com/cocktails/wheatley-75/
https://www.wheatleyvodka.com/cocktails/wheatley-vodka-rhubarb-mint-julep/
https://www.wheatleyvodka.com/cocktails/wheatley-vodka-blackberry-mint-julep/
https://www.wheatleyvodka.com/cocktails/the-new-caledonia/
https://www.wheatleyvodka.com/cocktails/cheap-sunglasses/
https://www.wheatleyvodka.com/cocktails/quince-md/
https://www.wheatleyvodka.com/cocktails/the-khaleesi/
https://www.wheatleyvodka.com/cocktails/waltzing-back/
https://www.wheatleyvodka.com/cocktails/cran-holiday-punch/
https://www.wheatleyvodka.com/cocktails/raspberry-lemonade/
https://www.wheatleyvodka.com/cocktails/wheatley-shandy/
https://www.wheatleyvodka.com/cocktails/wheatley-white-apple-sangria/
https://www.wheatleyvodka.com/cocktails/spiced-winter-punch/
