### ISSUE TITLE
Finish styling of the cocktails page

### ISSUE THREAD

**Issue by cziegeler** [hlxsites/sazerac-wheatleyvodka#50]
The cocktails page needs some fine tuning like margin/padding between blocks and handling the different breakpoints for all recipes correctly

**Comment by RemoLiechti** [comment]
also, there's some bugs with the load more functionality.

initially, missing one in the middle:
![image](https://github.com/hlxsites/sazerac-wheatleyvodka/assets/141611642/75c024e7-771d-4462-b952-b0531755749f)


when you load more, missing two:
![image](https://github.com/hlxsites/sazerac-wheatleyvodka/assets/141611642/6b52edba-9f8d-467f-be38-be5995aa4b6d)


press load more again, now seems to look right.
then you press load more again,again one missing:
![image](https://github.com/hlxsites/sazerac-wheatleyvodka/assets/141611642/5482c37b-3f34-4289-a8a8-441f099c070e)

press again, two missing.
press again, now really interesting: one is doubled!
![image](https://github.com/hlxsites/sazerac-wheatleyvodka/assets/141611642/3687818d-c7f7-449a-9edf-cb6f69b681f8)

**Comment by RemoLiechti** [comment]
when the load more button is pressed, it stays in hover mode until you click into the white area of the page.

**Comment by cziegeler** [comment]
Right, the loading function needs some improvement, too

**Comment by cziegeler** [comment]
@RemoLiechti I created a separate issue for the button as it is a general problem. #52
