### ISSUE TITLE
define global styles - check mobile version

### ISSUE THREAD

**Issue by RemoLiechti** [hlxsites/sazerac-wheatleyvodka#55]
in issue #27 any styles defined are based on desktop. seems like there are different ones for mobile.
check all styles we need for discrepancies on mobile.

**Comment by cziegeler** [comment]
when this is done it needs to be carefully checked whether styling on all pages and also nav/footer still is as expected

**Comment by karlpauls** [comment]
I'm going to close this issue - I think we should create new ones if we find differences.
